#   Ensure the mysql2 gem is defined in your Gemfile
#   gem 'mysql2'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
   adapter: mysql2
   database: buymart
   username: root
   password: root
   host: localhost